# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
remote_theme: mmistakes/so-simple-theme
local: en-US
title: My Personal Ngoprek Problems >_
email: naufalammarun11@gmail.com
description:
  My name is Ammar and this is my personal blog, documenting my journey
  on the quest to become the best person I can be.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ammarun.my.id" # the base hostname & protocol for your site, e.g. http://example.com
logo: "/images/code-logo.svg"
date_format: "%B %-d, %Y"
read_time: true
words_per_minute: 200
mathjax: true
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
google_analytics: UA-148949117-1
disqus:
  shortname: masalahngoprek
google_site_verification : "zKB-7_EmphHj7Wpc-lRmu7BjIVPWRvMJkoqWQQBSjEI"



paginate: 10
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Search
search_full_content: false


  # Site Author
author:
  name: Muhammad Naufal Ammar
  picture: /images/professional-headshot.jpg
  email:
  twitter: 
  links:
    - title: Twitter
      url: https://twitter.com/#
      icon: fab fa-twitter-square
    - title: GitHub
      url: https://github.com/ammarun11
      icon: fab fa-github-square
    - title: LinkedIn
      url: https://www.linkedin.com/in/#
      icon: fab fa-linkedin

# Footer Links
footer_links:
  - title: Twitter
    url: https://twitter.com/#
    icon: fab fa-twitter-square
  - title: GitHub
    url: https://github.com/ammarun11
    icon: fab fa-github-square
  - title: LinkedIn
    url: https://www.linkedin.com/in/#
    icon: fab fa-linkedin

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
